### ISSUE TITLE
Missing file scripts/train_cls.py

### ISSUE THREAD

**Issue by DunzhiZhou** [jdeschena/ddpm-zero-shot-interpolation#1]
Dear 
```
# Run from diff_exp directory
# The configs for evaluation classifiers are in configs/scripts/train_cls/eval_cls/
# For example, to train the smile evaluation classifier, run
python scripts/train_cls.py --cfg_from configs/scripts/train_cls/eval_cls/simple_smile_cls.yaml
```
``scripts/train_cls.py``
The file in the given path is missing, only ``train_cls_with_dataset_fabric.py`` exists. Could you double-check for this

**Comment by jdeschena** [comment]
Hi, really sorry about this issue. I will do my best to have it checked in the next 24h. Thank you for your interest in our work!

**Comment by jdeschena** [comment]
Hi, I have updated the readme and added a config file. It should be working now
